export const testClues = [
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b17",
        "gameID": 7583,
        "id": "75830",
        "category": "THE DIRECTOR'S CUT",
        "value": 200,
        "question": "In 2009 Steven Soderbergh was off the team & Bennett Miller was up to bat as director of this Brad Pitt drama",
        "answer": "Moneyball",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b18",
        "gameID": 7583,
        "id": "75831",
        "category": "ELECTRICITY",
        "value": 200,
        "img": true,
        "question": "The whiskers don't do the shocking on the electric type of this fish; it has specialized bio-electric organs",
        "answer": "a catfish",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b19",
        "gameID": 7583,
        "id": "75832",
        "category": "WHO WROTE IT?",
        "value": 200,
        "question": "\"Prince Lestat\"",
        "answer": "Anne Rice",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1a",
        "gameID": 7583,
        "id": "75833",
        "category": "N*P*R",
        "value": 200,
        "question": "This adjective meaning see-through can also mean open to public scrutiny",
        "answer": "transparent",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1b",
        "gameID": 7583,
        "id": "75834",
        "category": "ENGLISH MUFFINS",
        "value": 200,
        "question": "Lean Canadian bacon & English muffins are key ingredients of this McDonald's staple",
        "answer": "an Egg McMuffin",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1c",
        "gameID": 7583,
        "id": "75835",
        "category": "CROOKS & NANNIES",
        "value": 200,
        "question": "Elin Nordegren went from nannydom into marriage & then a $750 million divorce settlement from him",
        "answer": "Tiger Woods",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1d",
        "gameID": 7583,
        "id": "75836",
        "category": "THE DIRECTOR'S CUT",
        "value": 400,
        "question": "For this 1939 fantasy classic, Victor Fleming replaced George Cukor",
        "answer": "The Wizard of Oz",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1e",
        "gameID": 7583,
        "id": "75837",
        "category": "ELECTRICITY",
        "value": 400,
        "question": "Current in fluids has these charged atoms going in opposite directions depending on if they're positive or negative",
        "answer": "ions",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b1f",
        "gameID": 7583,
        "id": "75838",
        "category": "WHO WROTE IT?",
        "value": 400,
        "question": "\"Naked Lunch\"",
        "answer": "William S. Burroughs",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b20",
        "gameID": 7583,
        "id": "75839",
        "category": "N*P*R",
        "value": 400,
        "question": "Good news may make you \"turn\" these with joy",
        "answer": "handsprings",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b21",
        "gameID": 7583,
        "id": "758310",
        "category": "ENGLISH MUFFINS",
        "value": 400,
        "question": "foodandwine.com suggests a Caesar salad employing the English muffins' crunchiness in this role",
        "answer": "crouton",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b22",
        "gameID": 7583,
        "id": "758311",
        "category": "CROOKS & NANNIES",
        "value": 400,
        "question": "Unscrupulous 19th century financiers like James Fisk were known as \"robber\" these",
        "answer": "barons",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b23",
        "gameID": 7583,
        "id": "758312",
        "category": "THE DIRECTOR'S CUT",
        "value": 600,
        "question": "The original director of this 1977 classic about weekends at the disco was forced to boogie away",
        "answer": "Saturday Night Fever",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b24",
        "gameID": 7583,
        "id": "758313",
        "category": "ELECTRICITY",
        "value": 600,
        "question": "Luigi Galvani got a dead frog to twitch by touching metal to these during an electrical storm",
        "answer": "nerves",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b25",
        "gameID": 7583,
        "id": "758314",
        "category": "WHO WROTE IT?",
        "value": 600,
        "question": "\"The Screwtape Letters\"",
        "answer": "C.S. Lewis",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b26",
        "gameID": 7583,
        "id": "758315",
        "category": "N*P*R",
        "value": 600,
        "question": "It's another name for a movie's director of photography",
        "answer": "cinematographer",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b27",
        "gameID": 7583,
        "id": "758316",
        "category": "ENGLISH MUFFINS",
        "value": 600,
        "question": "This morning dish made with English muffins isn't named for an American traitor, but rather a Delmonico's patron",
        "answer": "Eggs Benedict",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b28",
        "gameID": 7583,
        "id": "758317",
        "category": "CROOKS & NANNIES",
        "value": 600,
        "question": "\"Supernanny\" Jo Frost has a \"naughty step\" where your little one sits for this period, one minute for each year old",
        "answer": "time-out",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b29",
        "gameID": 7583,
        "id": "758318",
        "category": "THE DIRECTOR'S CUT",
        "value": 800,
        "question": "Kirk Douglas got Anthony Mann cut from this 1960 gladiator epic & found young Stanley Kubrick to replace him",
        "answer": "Spartacus",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2a",
        "gameID": 7583,
        "id": "758319",
        "category": "ELECTRICITY",
        "value": 800,
        "question": "Many car batteries use a solution of sulfuric acid & water called this, also what Gatorade tries to replenish",
        "answer": "electrolytes",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2b",
        "gameID": 7583,
        "id": "758320",
        "category": "WHO WROTE IT?",
        "value": 800,
        "question": "\"Breakfast at Tiffany's\"",
        "answer": "Truman Capote",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2c",
        "gameID": 7583,
        "id": "758321",
        "category": "N*P*R",
        "value": 800,
        "question": "This small island nation is the largest port in southeast Asia",
        "answer": "Singapore",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2d",
        "gameID": 7583,
        "id": "758322",
        "category": "ENGLISH MUFFINS",
        "value": 800,
        "question": "\"Nooks & crannies\" is a trademark of this brand of English muffin",
        "answer": "Thomas",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2e",
        "gameID": 7583,
        "id": "758323",
        "category": "CROOKS & NANNIES",
        "value": 800,
        "img": true,
        "question": "Ironically, a lawman is carrying the weapon that gave this gangster his nickname",
        "answer": "Machine Gun Kelly",
        "dd": true,
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b2f",
        "gameID": 7583,
        "id": "758324",
        "category": "THE DIRECTOR'S CUT",
        "value": 1000,
        "question": "Original director Philip Kaufman had creative differences with this final director of \"The Outlaw Josey Wales\"",
        "answer": "Clint Eastwood",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b30",
        "gameID": 7583,
        "id": "758325",
        "category": "ELECTRICITY",
        "value": 1000,
        "question": "Rubber casings around copper wiring act as one of these retardants of electricity",
        "answer": "an insulator",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b31",
        "gameID": 7583,
        "id": "758326",
        "category": "WHO WROTE IT?",
        "value": 1000,
        "question": "\"Rumble Fish\" & \"That Was Then, This Is Now\"",
        "answer": "S.E. Hinton",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b32",
        "gameID": 7583,
        "id": "758327",
        "category": "N*P*R",
        "value": 1000,
        "question": "This naval vessel's purpose is to seek out & destroy floating enemy bombs",
        "answer": "a minesweeper",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b33",
        "gameID": 7583,
        "id": "758328",
        "category": "ENGLISH MUFFINS",
        "value": 1000,
        "question": "This teatime treat with a 7-letter name is basically an English muffin, though often served whole, not split",
        "answer": "a crumpet",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b34",
        "gameID": 7583,
        "id": "758329",
        "category": "CROOKS & NANNIES",
        "value": 1000,
        "question": "Maria Borrallo is nanny to these 2 royals who live in a big palace",
        "answer": "George and Charlotte",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b35",
        "gameID": 7583,
        "id": "758330",
        "category": "LUCKY 13th CENTURY",
        "value": 400,
        "question": "After the destruction of Baghdad in 1258, the Mamluks based their caliphate in this Egyptian city",
        "answer": "Cairo",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b36",
        "gameID": 7583,
        "id": "758331",
        "category": "BEE WORDS",
        "value": 400,
        "question": "Weals of urticaria are this itchy skin condition",
        "answer": "hives",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b37",
        "gameID": 7583,
        "id": "758332",
        "category": "ELECTIONS IN CANADA",
        "value": 400,
        "question": "The leader of the majority party in Canadian federal elections gets this job, natch",
        "answer": "prime minister",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b38",
        "gameID": 7583,
        "id": "758333",
        "category": "A TALE OF \"NEW\" CITIES",
        "value": 400,
        "question": "The Puritans found safety when they settled this Connecticut city in 1638",
        "answer": "New Haven",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b39",
        "gameID": 7583,
        "id": "758334",
        "category": "BRITANNICA BYLINES",
        "value": 400,
        "question": "He conjured up the entry on conjuring for the 1926 edition, the same year as his untimely death",
        "answer": "Harry Houdini",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3a",
        "gameID": 7583,
        "id": "758335",
        "category": "LYRICS FROM BROADWAY",
        "value": 400,
        "question": "\"Nobody knows in America Puerto Rico's in America!\"",
        "answer": "West Side Story",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3b",
        "gameID": 7583,
        "id": "758336",
        "category": "LUCKY 13th CENTURY",
        "value": 800,
        "question": "Obviously in no need of fertile land, Haakon IV of this country gained sovereignty over Greenland & Iceland",
        "answer": "Norway",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3c",
        "gameID": 7583,
        "id": "758337",
        "category": "BEE WORDS",
        "value": 800,
        "question": "Quadcopters being all the rage, ESPN now airs the DRL, or this Racing League",
        "answer": "drone",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3d",
        "gameID": 7583,
        "id": "758338",
        "category": "ELECTIONS IN CANADA",
        "value": 800,
        "question": "The party that wins the second-most seats is termed the \"official\" this other \"O\" word",
        "answer": "opposition",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3e",
        "gameID": 7583,
        "id": "758339",
        "category": "A TALE OF \"NEW\" CITIES",
        "value": 800,
        "question": "Founded in 1718, it was ceded to Spain in 1763, ceded to France in 1800 & sold to the U.S. in 1803",
        "answer": "New Orleans",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b3f",
        "gameID": 7583,
        "id": "758340",
        "category": "BRITANNICA BYLINES",
        "value": 800,
        "question": "Noted anarchist Prince Peter Alexeivitch Kropotkin wrote a 19th century entry on this capital",
        "answer": "Moscow (or Saint Petersburg)",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b40",
        "gameID": 7583,
        "id": "758341",
        "category": "LYRICS FROM BROADWAY",
        "value": 800,
        "question": "\"Sad to say your dream is not the kind of dream I'd like to get, Pharaoh has it in for you\"",
        "answer": "Joseph and the Amazing Technicolor Dreamcoat",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b41",
        "gameID": 7583,
        "id": "758342",
        "category": "LUCKY 13th CENTURY",
        "value": 1200,
        "img": true,
        "question": "The Louvre sees a new sense of humanity in a work by Cimabue, who it credits with the rebirth of painting in this country",
        "answer": "Italy",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b42",
        "gameID": 7583,
        "id": "758343",
        "category": "BEE WORDS",
        "value": 1200,
        "question": "Zeus & friends ate ambrosia & drank this",
        "answer": "nectar",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b43",
        "gameID": 7583,
        "id": "758344",
        "category": "ELECTIONS IN CANADA",
        "value": 1200,
        "question": "Unlike in the U.S., you can vote in Canada even while living in these, like the Saskatchewan federal one",
        "answer": "a prison",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b44",
        "gameID": 7583,
        "id": "758345",
        "category": "A TALE OF \"NEW\" CITIES",
        "value": 1200,
        "question": "Situated on the west bank of the Yamuna River, it was formally dedicated in 1931",
        "answer": "New Delhi",
        "dd": true,
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b45",
        "gameID": 7583,
        "id": "758346",
        "category": "BRITANNICA BYLINES",
        "value": 1200,
        "question": "No poser, Tony Hawk busted out the rad entry on this",
        "answer": "skateboarding",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b46",
        "gameID": 7583,
        "id": "758347",
        "category": "LYRICS FROM BROADWAY",
        "value": 1200,
        "question": "\"And God said, 'Joe, people really need to know that the Bible isn't two parts, there's a part three'\"",
        "answer": "The Book of Mormon",
        "dd": true,
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b47",
        "gameID": 7583,
        "id": "758348",
        "category": "LUCKY 13th CENTURY",
        "value": 1600,
        "question": "By the 1270s this Dominican saint was summing up the religious thought of his time in the \"Summa Theologica\"",
        "answer": "Thomas Aquinas",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b48",
        "gameID": 7583,
        "id": "758349",
        "category": "BEE WORDS",
        "value": 1600,
        "question": "These \"words\" by definition are in vogue & culturally trendy",
        "answer": "buzzwords",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b49",
        "gameID": 7583,
        "id": "758350",
        "category": "ELECTIONS IN CANADA",
        "value": 1600,
        "question": "In a 2014 provincial election, Philippe Couillard & the Liberals beat Pauline Marois & the PQ, or Parti this",
        "answer": "Quebecois",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4a",
        "gameID": 7583,
        "id": "758351",
        "category": "A TALE OF \"NEW\" CITIES",
        "value": 1600,
        "question": "An annual \"Moby Dick\" marathon takes place at this Massachusetts city's whaling museum",
        "answer": "New Bedford",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4b",
        "gameID": 7583,
        "id": "758352",
        "category": "BRITANNICA BYLINES",
        "value": 1600,
        "question": "This naturalist's 1902 article on Yosemite stated that Vernal Falls was \"famous for its afternoon rainbows\"",
        "answer": "(John) Muir",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4c",
        "gameID": 7583,
        "id": "758353",
        "category": "LYRICS FROM BROADWAY",
        "value": 1600,
        "question": "\"Kiss today goodbye, the sweetness & the sorrow\"",
        "answer": "A Chorus Line",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4d",
        "gameID": 7583,
        "id": "758354",
        "category": "LUCKY 13th CENTURY",
        "value": 2000,
        "question": "In 1258 an Anglo-French treaty ended decades of conflict between the Plantagenets & this dynasty",
        "answer": "the Capetian",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4e",
        "gameID": 7583,
        "id": "758355",
        "category": "BEE WORDS",
        "value": 2000,
        "question": "A rani is one of these",
        "answer": "a queen",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b4f",
        "gameID": 7583,
        "id": "758356",
        "category": "ELECTIONS IN CANADA",
        "value": 2000,
        "question": "Gallop to this term for federal election districts; they don't have numbers but names like Madawaska-Restigouche",
        "answer": "the ridings",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b50",
        "gameID": 7583,
        "id": "758357",
        "category": "A TALE OF \"NEW\" CITIES",
        "value": 2000,
        "question": "Founded in 1639, this Rhode Island town flourished thanks to its excellent harbor",
        "answer": "Newport",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b51",
        "gameID": 7583,
        "id": "758358",
        "category": "BRITANNICA BYLINES",
        "value": 2000,
        "question": "Who better than this holy man to write the entry on South Africa's 1995 Truth and Reconciliation Commission?",
        "answer": "Desmond Tutu",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b52",
        "gameID": 7583,
        "id": "758359",
        "category": "LYRICS FROM BROADWAY",
        "value": 2000,
        "question": "\"High in her tower, she sits by the hour, maintaining her hair\"",
        "answer": "Into the Woods",
        "__v": 0
    },
    {
        "played": false,
        "_id": "61aab2f8f06c0f39a7d62b53",
        "gameID": 7583,
        "id": "758360",
        "category": "NOVELS",
        "question": "\"A man can be destroyed but not defeated\" is a line from this 1952 book, later a Spencer Tracy film",
        "answer": "The Old Man and the Sea",
        "__v": 0
    }
]