// COMPONENT RESPONSIBLE FOR CREATING CATEGORY COLUMNS
// EACH COLUMN WILL DISPLAY THE "CATEGORY NAME" AT THE TOP AND RENDER 5 CLUES WITH MATCHING CATEGORIES, ARRANGED BY VALUE ($ -> $$$).

import React from 'react';
import Clue from './Clue';
